### ISSUE TITLE
version 1.0.6 issue

### ISSUE THREAD

**Issue by seema84** [strangerstudios/basic-user-avatars#50]
Hello,

since the latest version the prioritization does not work properly for me anymore.

I also use this plugin:
https://de.wordpress.org/plugins/minotar-minecraft-avatars/

Before the last update (1.0.6), the prioritization was like this:

Custom Avatar (Upload) > Minotar > Default Avatar 

But now i cant add a Custom Avatar if a Minotar Avatar was found.

**Comment by andrewlimaza** [comment]
Hi @seema84 

We try our best to ensure that updates don't cause conflicts like this. However, the Minotar Minecraft Avatars is outdated (Tested with WordPress 3.6) which may be causing issues as we're following the latest WordPress functions to handle avatars.

Can you please share a screenshot of your issue?

A temporary solution would be to rollback to version 1.0.5 instead.

**Comment by seema84** [comment]
What screenshot do you need for the problem?

![6675](https://user-images.githubusercontent.com/2832339/126079955-bbd0a8e8-784a-488f-bb19-885d4ad349a1.PNG)

**Comment by seema84** [comment]
A possibility to set the priority (between gravatar and avatar uploaded on the page) would be helpful.

**Comment by JarrydLong** [comment]
Considering Minotar is no longer supported as it last received an update 9+ years ago, I'm not sure if this is something we're going to fix. If this becomes a more common issue among other, more updated plugins, we can investigate - however: 

Looking at how we currently use our avatars, there are improvements/adjustments that can be made, including adding the Basic User Avatars option as a default option under the Avatar settings found under Settings > Discussion:

![image](https://user-images.githubusercontent.com/8989542/212093745-8155adff-7f71-464e-8872-9c00abec567f.png)

Implementing something like this allows us to give preference to a Basic User Avatars avatar over others, but doesn't entirely fix the problem that has been discussed in this issue (of one giving preference over the other one when another has been set etc)

**Comment by seema84** [comment]
I'm not sure if it's really minotar (which works fine by the way). For me it looks more like the prioritization in Basic User Avatars. Something must have changed in 1.0.6. This concerns not only minotar but also gravatar.

**Comment by andrewlimaza** [comment]
I've run further tests and the issue seems to happen on V1.0.6 and other newer versions. The reason being is that the Minotar plugin is not compatible with other Avatar plugins. (It always shows the Minotar minecraft head regardless if I am using a custom avatar).

They are loading their code at the lowest priority available without it being filterable. You may need to tweak the Minotar code directly to support custom uploaded avatars from Basic User Avatars.

Please have a look at the `add_filter( 'get_avatar', array( $this, 'get_minotar_avatar' ), 1, 5 );` filter within their plugin's code to create a compatibility between the two plugins as there is no easy way for us to filter it.

Thank you for understanding, I'm sorry about any inconvenience caused by this as it is out of our control.
