### ISSUE TITLE
Avatar not updated

### ISSUE THREAD

**Issue by Zazou49** [strangerstudios/Basic-User-Avatars#60]
Hello,

I'm using [Theme My Login](https://wordpress.org/plugins/theme-my-login/) plugin to create a frontend user profile. If I enable the plugin, I can see the avatar box on the page, upload a new avatar but when I update my profile, avatar isn't updated.

Wordpress 5.9.3
Basic User Avatar 1.0.7

Thank you

**Comment by JarrydLong** [comment]
Thanks for the heads up on this @Zazou49 

I've tested this with Basic User Avatar 1.0.7 and Theme My Login 7.1.5 but haven't been able to replicate the issue. This might have been caused by a bug or conflict on TML's side that has been resolved since reporting this issue. 

If it happens again feel free to open a support ticket or issue and we can take a look.
